targets:
  $default:
    builders:
      freezed:
        options:
          copy_with: true
          equal: true
          to_string: false

      json_serializable:
        options:
          field_rename: none
          explicit_to_json: true
          include_if_null: false