name: chatting_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.2
  go_router: ^17.3.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  dartz: ^0.10.1
  get_it: ^9.2.1
  injectable: ^3.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.12.0
  easy_localization: ^3.0.8
  shared_preferences: ^2.5.5
  image_picker: ^1.2.2
  image: ^4.8.0
  cached_network_image: ^3.4.1
  package_info_plus: ^10.1.0
  flutter_svg: ^2.3.0
  flutter_slidable: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  inject_annotation: ^1.0.1
  injectable_generator: ^3.0.2
  freezed: ^3.2.5
  json_serializable: ^6.14.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/translations/
    - assets/svg_icons/
